// <auto-generated />
namespace _19DTHA_A_DO_AN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addName1Identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addName1Identity));
        
        string IMigrationMetadata.Id
        {
            get { return "202107230122223_addName1Identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
